# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/my-manager-v1/ui/dialog_create_real_estate.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateRealEstate(object):
    def setupUi(self, DialogCreateRealEstate):
        DialogCreateRealEstate.setObjectName("DialogCreateRealEstate")
        DialogCreateRealEstate.resize(396, 722)
        DialogCreateRealEstate.setMaximumSize(QtCore.QSize(16777209, 16777215))
        DialogCreateRealEstate.setStyleSheet("QRadioButton {\n"
"  background-color: rgb(240, 242, 246);\n"
"  color: rgb(90, 93, 97);\n"
"  border: 2px solid #CED4DA;\n"
"  padding: 4px 8px; /* Tạo khoảng đệm bên trong */\n"
"  border-radius: 8px; /* Bo tròn góc */\n"
"  text-align: center; /* Căn giữa chữ */\n"
"  font-weight: 600;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"  width: 0px;\n"
"  height: 0px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"  background-color: rgb(230, 231, 242);\n"
"}\n"
"\n"
"QRadioButton:pressed {\n"
"  background-color: #bbb;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"  color: #007BFF;\n"
"  border: 1px solid #007BFF;\n"
"}\n"
"\n"
"QRadioButton:checked:hover {\n"
"  background-color: #cce0ff; /* Màu nền khi được chọn và hover */\n"
"}\n"
"\n"
"QRadioButton:checked:pressed {\n"
"  background-color: #aaccee; /* Màu nền khi được chọn và pressed */\n"
"}\n"
"\n"
"QLabel {\n"
"color: rgb(90, 93, 97);\n"
"border: none;\n"
"font-weight: 600;\n"
"font-size: 12px;\n"
"}\n"
"QLineEdit {\n"
"border: 1px solid #CED4DA;\n"
"padding: 2px 4px;\n"
"border-radius: 8px;\n"
"}\n"
"QPlainTextEdit{\n"
"  border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogCreateRealEstate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.images = QtWidgets.QWidget(parent=DialogCreateRealEstate)
        self.images.setMinimumSize(QtCore.QSize(0, 200))
        self.images.setMaximumSize(QtCore.QSize(16777215, 200))
        self.images.setStyleSheet("border: 2px dashed #CED4DA;\n"
"border-radius: 8px;")
        self.images.setObjectName("images")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.images)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.images_label = QtWidgets.QLabel(parent=self.images)
        self.images_label.setStyleSheet("\n"
"  color: rgb(90, 93, 97);\n"
"border: none;\n"
"font-weight: 800;")
        self.images_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.images_label.setObjectName("images_label")
        self.horizontalLayout.addWidget(self.images_label)
        self.verticalLayout.addWidget(self.images)
        self.location_info = QtWidgets.QWidget(parent=DialogCreateRealEstate)
        self.location_info.setObjectName("location_info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.location_info)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.location__districts = QtWidgets.QComboBox(parent=self.location_info)
        self.location__districts.setStyleSheet("")
        self.location__districts.setObjectName("location__districts")
        self.location__districts.addItem("")
        self.gridLayout.addWidget(self.location__districts, 0, 2, 1, 1)
        self.location__provices = QtWidgets.QComboBox(parent=self.location_info)
        self.location__provices.setObjectName("location__provices")
        self.location__provices.addItem("")
        self.gridLayout.addWidget(self.location__provices, 0, 1, 1, 1)
        self.location__wards = QtWidgets.QComboBox(parent=self.location_info)
        self.location__wards.setObjectName("location__wards")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.location__wards.addItem("")
        self.gridLayout.addWidget(self.location__wards, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.location__street_label = QtWidgets.QLabel(parent=self.location_info)
        self.location__street_label.setObjectName("location__street_label")
        self.horizontalLayout_2.addWidget(self.location__street_label)
        self.location__street = QtWidgets.QLineEdit(parent=self.location_info)
        self.location__street.setObjectName("location__street")
        self.horizontalLayout_2.addWidget(self.location__street)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.location_info)
        self.basic_info = QtWidgets.QWidget(parent=DialogCreateRealEstate)
        self.basic_info.setObjectName("basic_info")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.basic_info)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.basic__options = QtWidgets.QWidget(parent=self.basic_info)
        self.basic__options.setStyleSheet("")
        self.basic__options.setObjectName("basic__options")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.basic__options)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.options__sell = QtWidgets.QRadioButton(parent=self.basic__options)
        self.options__sell.setStyleSheet("")
        self.options__sell.setChecked(True)
        self.options__sell.setObjectName("options__sell")
        self.horizontalLayout_3.addWidget(self.options__sell)
        self.options__rent = QtWidgets.QRadioButton(parent=self.basic__options)
        self.options__rent.setStyleSheet("")
        self.options__rent.setObjectName("options__rent")
        self.horizontalLayout_3.addWidget(self.options__rent)
        self.options__assignment = QtWidgets.QRadioButton(parent=self.basic__options)
        self.options__assignment.setStyleSheet("")
        self.options__assignment.setObjectName("options__assignment")
        self.horizontalLayout_3.addWidget(self.options__assignment)
        self.verticalLayout_5.addWidget(self.basic__options)
        self.basic__categories = QtWidgets.QComboBox(parent=self.basic_info)
        self.basic__categories.setObjectName("basic__categories")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.basic__categories.addItem("")
        self.verticalLayout_5.addWidget(self.basic__categories)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout.addWidget(self.basic_info)
        self.detail_info = QtWidgets.QWidget(parent=DialogCreateRealEstate)
        self.detail_info.setObjectName("detail_info")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.detail_info)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(4, 4, 4, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.legal = QtWidgets.QComboBox(parent=self.detail_info)
        self.legal.setObjectName("legal")
        self.legal.addItem("")
        self.legal.addItem("")
        self.legal.addItem("")
        self.legal.addItem("")
        self.legal.addItem("")
        self.legal.addItem("")
        self.legal.addItem("")
        self.gridLayout_3.addWidget(self.legal, 3, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.detail__area_label = QtWidgets.QLabel(parent=self.detail_info)
        self.detail__area_label.setObjectName("detail__area_label")
        self.horizontalLayout_7.addWidget(self.detail__area_label)
        self.detail__ = QtWidgets.QLineEdit(parent=self.detail_info)
        self.detail__.setObjectName("detail__")
        self.horizontalLayout_7.addWidget(self.detail__)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.furniture = QtWidgets.QComboBox(parent=self.detail_info)
        self.furniture.setObjectName("furniture")
        self.furniture.addItem("")
        self.furniture.addItem("")
        self.furniture.addItem("")
        self.gridLayout_3.addWidget(self.furniture, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.detail__structure_label = QtWidgets.QLabel(parent=self.detail_info)
        self.detail__structure_label.setObjectName("detail__structure_label")
        self.horizontalLayout_5.addWidget(self.detail__structure_label)
        self.detail__structure = QtWidgets.QLineEdit(parent=self.detail_info)
        self.detail__structure.setObjectName("detail__structure")
        self.horizontalLayout_5.addWidget(self.detail__structure)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.detail__function_label = QtWidgets.QLabel(parent=self.detail_info)
        self.detail__function_label.setObjectName("detail__function_label")
        self.horizontalLayout_6.addWidget(self.detail__function_label)
        self.detail__function = QtWidgets.QLineEdit(parent=self.detail_info)
        self.detail__function.setObjectName("detail__function")
        self.horizontalLayout_6.addWidget(self.detail__function)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.detail__price_label = QtWidgets.QLabel(parent=self.detail_info)
        self.detail__price_label.setObjectName("detail__price_label")
        self.horizontalLayout_8.addWidget(self.detail__price_label)
        self.detail__price = QtWidgets.QLineEdit(parent=self.detail_info)
        self.detail__price.setObjectName("detail__price")
        self.horizontalLayout_8.addWidget(self.detail__price)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.building_line = QtWidgets.QComboBox(parent=self.detail_info)
        self.building_line.setObjectName("building_line")
        self.building_line.addItem("")
        self.building_line.addItem("")
        self.gridLayout_3.addWidget(self.building_line, 2, 0, 1, 1)
        self.description = QtWidgets.QPlainTextEdit(parent=self.detail_info)
        self.description.setObjectName("description")
        self.gridLayout_3.addWidget(self.description, 4, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.detail_info)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogCreateRealEstate)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DialogCreateRealEstate)
        self.buttonBox.accepted.connect(DialogCreateRealEstate.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogCreateRealEstate.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogCreateRealEstate)

    def retranslateUi(self, DialogCreateRealEstate):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateRealEstate.setWindowTitle(_translate("DialogCreateRealEstate", "Dialog"))
        self.images_label.setText(_translate("DialogCreateRealEstate", "Kéo và thả hình ảnh ..."))
        self.location__districts.setItemText(0, _translate("DialogCreateRealEstate", "Đà Lạt"))
        self.location__provices.setItemText(0, _translate("DialogCreateRealEstate", "Lâm Đồng"))
        self.location__wards.setItemText(0, _translate("DialogCreateRealEstate", "Phường 1"))
        self.location__wards.setItemText(1, _translate("DialogCreateRealEstate", "Phường 2"))
        self.location__wards.setItemText(2, _translate("DialogCreateRealEstate", "Phường 3"))
        self.location__wards.setItemText(3, _translate("DialogCreateRealEstate", "Phường 4"))
        self.location__wards.setItemText(4, _translate("DialogCreateRealEstate", "Phường 5"))
        self.location__wards.setItemText(5, _translate("DialogCreateRealEstate", "Phường 6"))
        self.location__wards.setItemText(6, _translate("DialogCreateRealEstate", "Phường 7"))
        self.location__wards.setItemText(7, _translate("DialogCreateRealEstate", "Phường 8"))
        self.location__wards.setItemText(8, _translate("DialogCreateRealEstate", "Phường 9"))
        self.location__wards.setItemText(9, _translate("DialogCreateRealEstate", "Phường 10"))
        self.location__wards.setItemText(10, _translate("DialogCreateRealEstate", "Phường 11"))
        self.location__wards.setItemText(11, _translate("DialogCreateRealEstate", "Phường 12"))
        self.location__wards.setItemText(12, _translate("DialogCreateRealEstate", "Xã Tà Nung"))
        self.location__wards.setItemText(13, _translate("DialogCreateRealEstate", "Xã Trạm Hành"))
        self.location__wards.setItemText(14, _translate("DialogCreateRealEstate", "Xã Xuân Trường"))
        self.location__wards.setItemText(15, _translate("DialogCreateRealEstate", "Xã Xuân Thọ"))
        self.location__street_label.setText(_translate("DialogCreateRealEstate", "Tên đường"))
        self.options__sell.setText(_translate("DialogCreateRealEstate", "Bán"))
        self.options__rent.setText(_translate("DialogCreateRealEstate", "Cho thuê"))
        self.options__assignment.setText(_translate("DialogCreateRealEstate", "Sang nghượng"))
        self.basic__categories.setItemText(0, _translate("DialogCreateRealEstate", "Nhà"))
        self.basic__categories.setItemText(1, _translate("DialogCreateRealEstate", "Nhà mặt tiền"))
        self.basic__categories.setItemText(2, _translate("DialogCreateRealEstate", "Biệt thự"))
        self.basic__categories.setItemText(3, _translate("DialogCreateRealEstate", "Căn hộ chung cư"))
        self.basic__categories.setItemText(4, _translate("DialogCreateRealEstate", "Khách sạn"))
        self.basic__categories.setItemText(5, _translate("DialogCreateRealEstate", "Homestay"))
        self.basic__categories.setItemText(6, _translate("DialogCreateRealEstate", "Đất"))
        self.basic__categories.setItemText(7, _translate("DialogCreateRealEstate", "MBKD"))
        self.basic__categories.setItemText(8, _translate("DialogCreateRealEstate", "Kho"))
        self.legal.setItemText(0, _translate("DialogCreateRealEstate", "Không sổ"))
        self.legal.setItemText(1, _translate("DialogCreateRealEstate", "Sổ nông nghiệp chung"))
        self.legal.setItemText(2, _translate("DialogCreateRealEstate", "Sổ nông nghiệp phân quyền"))
        self.legal.setItemText(3, _translate("DialogCreateRealEstate", "Sổ nông nghiệp riêng"))
        self.legal.setItemText(4, _translate("DialogCreateRealEstate", "Sổ xây dựng chung"))
        self.legal.setItemText(5, _translate("DialogCreateRealEstate", "Sổ xây dựng phân quyền"))
        self.legal.setItemText(6, _translate("DialogCreateRealEstate", "Sổ xây dựng riêng"))
        self.detail__area_label.setText(_translate("DialogCreateRealEstate", "Diện tích"))
        self.furniture.setItemText(0, _translate("DialogCreateRealEstate", "Không nội thất"))
        self.furniture.setItemText(1, _translate("DialogCreateRealEstate", "Nội thất cơ bản"))
        self.furniture.setItemText(2, _translate("DialogCreateRealEstate", "Đầy đủ nội thất"))
        self.detail__structure_label.setText(_translate("DialogCreateRealEstate", "Kết cấu"))
        self.detail__function_label.setText(_translate("DialogCreateRealEstate", "Công năng"))
        self.detail__price_label.setText(_translate("DialogCreateRealEstate", "Giá"))
        self.building_line.setItemText(0, _translate("DialogCreateRealEstate", "Đường xe máy"))
        self.building_line.setItemText(1, _translate("DialogCreateRealEstate", "Đường xe hơi"))
        self.description.setPlaceholderText(_translate("DialogCreateRealEstate", "Thêm mô tả"))
