# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/qt-test/test/dialog_add_employee.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogAddEmployee(object):
    def setupUi(self, DialogAddEmployee):
        DialogAddEmployee.setObjectName("DialogAddEmployee")
        DialogAddEmployee.resize(480, 369)
        DialogAddEmployee.setStyleSheet("QLineEdit {\n"
"border: 1px solid #ccc;\n"
"border-radius: 8px;\n"
"padding: 4px 0;\n"
"}\n"
"QLabel {\n"
"font-size: 14px;\n"
"font-weight: 400;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogAddEmployee)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=DialogAddEmployee)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_username = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.input_username = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.input_username.setStyleSheet("")
        self.input_username.setObjectName("input_username")
        self.horizontalLayout.addWidget(self.input_username)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 431, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_password = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_2.addWidget(self.label_password)
        self.input_password = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.input_password.setObjectName("input_password")
        self.horizontalLayout_2.addWidget(self.input_password)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 210, 431, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_email = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout_3.addWidget(self.label_email)
        self.input_email = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_3)
        self.input_email.setObjectName("input_email")
        self.horizontalLayout_3.addWidget(self.input_email)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonbox = QtWidgets.QDialogButtonBox(parent=DialogAddEmployee)
        self.buttonbox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonbox.setObjectName("buttonbox")
        self.verticalLayout_2.addWidget(self.buttonbox)

        self.retranslateUi(DialogAddEmployee)
        self.buttonbox.accepted.connect(DialogAddEmployee.accept) # type: ignore
        self.buttonbox.rejected.connect(DialogAddEmployee.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAddEmployee)

    def retranslateUi(self, DialogAddEmployee):
        _translate = QtCore.QCoreApplication.translate
        DialogAddEmployee.setWindowTitle(_translate("DialogAddEmployee", "Dialog"))
        self.label_username.setText(_translate("DialogAddEmployee", "username"))
        self.label_password.setText(_translate("DialogAddEmployee", "password"))
        self.label_email.setText(_translate("DialogAddEmployee", "email"))
