# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager.v1/ui/dialog_create_real_estate.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCreateRealEstate(object):
    def setupUi(self, DialogCreateRealEstate):
        DialogCreateRealEstate.setObjectName("DialogCreateRealEstate")
        DialogCreateRealEstate.resize(517, 708)
        DialogCreateRealEstate.setMaximumSize(QtCore.QSize(517, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setItalic(False)
        DialogCreateRealEstate.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogCreateRealEstate)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialog_container = QtWidgets.QWidget(parent=DialogCreateRealEstate)
        self.dialog_container.setMinimumSize(QtCore.QSize(0, 0))
        self.dialog_container.setObjectName("dialog_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dialog_container)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image_container = QtWidgets.QWidget(parent=self.dialog_container)
        self.image_container.setObjectName("image_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.image_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.images = QtWidgets.QLabel(parent=self.image_container)
        self.images.setMinimumSize(QtCore.QSize(0, 160))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.images.setFont(font)
        self.images.setStyleSheet("font-size: 16px;\n"
"font-weight: 600;\n"
"color: #343A40;\n"
"border-radius: 8px;\n"
"border: 2px dashed #CED4DA;")
        self.images.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.images.setObjectName("images")
        self.verticalLayout_10.addWidget(self.images)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_4.addWidget(self.image_container)
        self.option_container = QtWidgets.QGroupBox(parent=self.dialog_container)
        self.option_container.setTitle("")
        self.option_container.setObjectName("option_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.option_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sell = QtWidgets.QRadioButton(parent=self.option_container)
        self.sell.setObjectName("sell")
        self.horizontalLayout.addWidget(self.sell)
        self.rent = QtWidgets.QRadioButton(parent=self.option_container)
        self.rent.setObjectName("rent")
        self.horizontalLayout.addWidget(self.rent)
        self.assignment = QtWidgets.QRadioButton(parent=self.option_container)
        self.assignment.setObjectName("assignment")
        self.horizontalLayout.addWidget(self.assignment)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.option_container)
        self.basic_container = QtWidgets.QWidget(parent=self.dialog_container)
        self.basic_container.setObjectName("basic_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.basic_container)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pid = QtWidgets.QLabel(parent=self.basic_container)
        self.pid.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pid.setObjectName("pid")
        self.horizontalLayout_3.addWidget(self.pid)
        self.category = QtWidgets.QComboBox(parent=self.basic_container)
        self.category.setObjectName("category")
        self.horizontalLayout_3.addWidget(self.category)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.basic_container)
        self.location_container = QtWidgets.QWidget(parent=self.dialog_container)
        self.location_container.setObjectName("location_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.location_container)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ward = QtWidgets.QComboBox(parent=self.location_container)
        self.ward.setObjectName("ward")
        self.gridLayout_4.addWidget(self.ward, 0, 2, 1, 1)
        self.district = QtWidgets.QComboBox(parent=self.location_container)
        self.district.setObjectName("district")
        self.gridLayout_4.addWidget(self.district, 0, 1, 1, 1)
        self.street = QtWidgets.QLineEdit(parent=self.location_container)
        self.street.setStyleSheet("QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"}")
        self.street.setObjectName("street")
        self.gridLayout_4.addWidget(self.street, 1, 0, 1, 3)
        self.province = QtWidgets.QComboBox(parent=self.location_container)
        self.province.setObjectName("province")
        self.gridLayout_4.addWidget(self.province, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.location_container)
        self.detail_container = QtWidgets.QWidget(parent=self.dialog_container)
        self.detail_container.setObjectName("detail_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.detail_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.structure_container = QtWidgets.QWidget(parent=self.detail_container)
        self.structure_container.setMinimumSize(QtCore.QSize(0, 0))
        self.structure_container.setStyleSheet("QLabel {\n"
"color: rgb(90, 93, 97);\n"
"font-size: 12px;\n"
"font-weight: 500;\n"
"}\n"
"QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"}")
        self.structure_container.setObjectName("structure_container")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.structure_container)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.structure_label = QtWidgets.QLabel(parent=self.structure_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.structure_label.setFont(font)
        self.structure_label.setLineWidth(1)
        self.structure_label.setMidLineWidth(0)
        self.structure_label.setIndent(0)
        self.structure_label.setObjectName("structure_label")
        self.verticalLayout_25.addWidget(self.structure_label)
        self.structure = QtWidgets.QLineEdit(parent=self.structure_container)
        self.structure.setObjectName("structure")
        self.verticalLayout_25.addWidget(self.structure)
        self.verticalLayout_24.addLayout(self.verticalLayout_25)
        self.gridLayout.addWidget(self.structure_container, 1, 3, 1, 2)
        self.function_container = QtWidgets.QWidget(parent=self.detail_container)
        self.function_container.setStyleSheet("QLabel {\n"
"color: rgb(90, 93, 97);\n"
"font-size: 12px;\n"
"font-weight: 500;\n"
"}\n"
"QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"}")
        self.function_container.setObjectName("function_container")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.function_container)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.function_label = QtWidgets.QLabel(parent=self.function_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.function_label.setFont(font)
        self.function_label.setLineWidth(1)
        self.function_label.setMidLineWidth(0)
        self.function_label.setIndent(0)
        self.function_label.setObjectName("function_label")
        self.verticalLayout_17.addWidget(self.function_label)
        self.function = QtWidgets.QLineEdit(parent=self.function_container)
        self.function.setObjectName("function")
        self.verticalLayout_17.addWidget(self.function)
        self.verticalLayout_16.addLayout(self.verticalLayout_17)
        self.gridLayout.addWidget(self.function_container, 1, 0, 1, 3)
        self.price_container = QtWidgets.QWidget(parent=self.detail_container)
        self.price_container.setStyleSheet("QLabel {\n"
"color: rgb(90, 93, 97);\n"
"font-size: 12px;\n"
"font-weight: 500;\n"
"}\n"
"QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"}")
        self.price_container.setObjectName("price_container")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.price_container)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.price_label = QtWidgets.QLabel(parent=self.price_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.price_label.setFont(font)
        self.price_label.setLineWidth(1)
        self.price_label.setMidLineWidth(0)
        self.price_label.setIndent(0)
        self.price_label.setObjectName("price_label")
        self.verticalLayout_19.addWidget(self.price_label)
        self.price = QtWidgets.QLineEdit(parent=self.price_container)
        self.price.setObjectName("price")
        self.verticalLayout_19.addWidget(self.price)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.gridLayout.addWidget(self.price_container, 0, 3, 1, 2)
        self.building_line = QtWidgets.QComboBox(parent=self.detail_container)
        self.building_line.setObjectName("building_line")
        self.gridLayout.addWidget(self.building_line, 2, 0, 1, 2)
        self.legal = QtWidgets.QComboBox(parent=self.detail_container)
        self.legal.setObjectName("legal")
        self.gridLayout.addWidget(self.legal, 2, 3, 1, 2)
        self.area_container = QtWidgets.QWidget(parent=self.detail_container)
        self.area_container.setToolTipDuration(-1)
        self.area_container.setStyleSheet("QLabel {\n"
"color: rgb(90, 93, 97);\n"
"font-size: 12px;\n"
"font-weight: 500;\n"
"}\n"
"QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"}")
        self.area_container.setObjectName("area_container")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.area_container)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.area_label = QtWidgets.QLabel(parent=self.area_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.area_label.setFont(font)
        self.area_label.setLineWidth(0)
        self.area_label.setMidLineWidth(0)
        self.area_label.setIndent(0)
        self.area_label.setObjectName("area_label")
        self.verticalLayout_7.addWidget(self.area_label)
        self.area = QtWidgets.QLineEdit(parent=self.area_container)
        self.area.setObjectName("area")
        self.verticalLayout_7.addWidget(self.area)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout.addWidget(self.area_container, 0, 0, 1, 3)
        self.furniture = QtWidgets.QComboBox(parent=self.detail_container)
        self.furniture.setObjectName("furniture")
        self.gridLayout.addWidget(self.furniture, 2, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.detail_container)
        self.description_container = QtWidgets.QWidget(parent=self.dialog_container)
        self.description_container.setStyleSheet("QLabel {\n"
"color: rgb(90, 93, 97);\n"
"font-size: 12px;\n"
"font-weight: 500;\n"
"}\n"
"QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"}")
        self.description_container.setObjectName("description_container")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.description_container)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.description_label = QtWidgets.QLabel(parent=self.description_container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.description_label.setFont(font)
        self.description_label.setLineWidth(1)
        self.description_label.setMidLineWidth(0)
        self.description_label.setIndent(0)
        self.description_label.setObjectName("description_label")
        self.verticalLayout_27.addWidget(self.description_label)
        self.description = QtWidgets.QPlainTextEdit(parent=self.description_container)
        self.description.setObjectName("description")
        self.verticalLayout_27.addWidget(self.description)
        self.verticalLayout_26.addLayout(self.verticalLayout_27)
        self.verticalLayout_4.addWidget(self.description_container)
        self.verticalLayout.addWidget(self.dialog_container)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogCreateRealEstate)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DialogCreateRealEstate)
        self.buttonBox.accepted.connect(DialogCreateRealEstate.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogCreateRealEstate.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogCreateRealEstate)

    def retranslateUi(self, DialogCreateRealEstate):
        _translate = QtCore.QCoreApplication.translate
        DialogCreateRealEstate.setWindowTitle(_translate("DialogCreateRealEstate", "Dialog"))
        self.images.setText(_translate("DialogCreateRealEstate", "Kéo & thả hình ảnh ..."))
        self.sell.setText(_translate("DialogCreateRealEstate", "Bán"))
        self.rent.setText(_translate("DialogCreateRealEstate", "Cho thuê"))
        self.assignment.setText(_translate("DialogCreateRealEstate", "Sang nhượng"))
        self.pid.setText(_translate("DialogCreateRealEstate", "PID: "))
        self.structure_label.setText(_translate("DialogCreateRealEstate", "Kết cấu"))
        self.function_label.setText(_translate("DialogCreateRealEstate", "Công năng"))
        self.price_label.setText(_translate("DialogCreateRealEstate", "Giá"))
        self.area_label.setText(_translate("DialogCreateRealEstate", "Diện tích"))
        self.description_label.setText(_translate("DialogCreateRealEstate", "Mô tả"))
