# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager.v1/ui/dialog_product_settings.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductSettings(object):
    def setupUi(self, ProductSettings):
        ProductSettings.setObjectName("ProductSettings")
        ProductSettings.resize(480, 346)
        ProductSettings.setStyleSheet("QDialog {\n"
"    font-family: \"Courier New\";\n"
"}\n"
"QLabel{\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"    color: rgb(90, 93, 97);\n"
"    max-height: 14px;\n"
"}\n"
"QLineEdit {\n"
"padding: 4px 0;\n"
"border: 1px solid #CED4DA;\n"
"border-radius: 8px;\n"
"margin-left: 8px;\n"
"padding-left: 4px;\n"
"}\n"
"QRadioButton{\n"
"font-family: \"Courier New\";\n"
"}")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ProductSettings)
        self.verticalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(parent=ProductSettings)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setContentsMargins(8, 4, 8, 4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.categories_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.categories_radio.setObjectName("categories_radio")
        self.gridLayout_4.addWidget(self.categories_radio, 0, 1, 1, 1)
        self.districts_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.districts_radio.setObjectName("districts_radio")
        self.gridLayout_4.addWidget(self.districts_radio, 0, 3, 1, 1)
        self.options_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.options_radio.setObjectName("options_radio")
        self.gridLayout_4.addWidget(self.options_radio, 0, 0, 1, 1)
        self.provinces_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.provinces_radio.setObjectName("provinces_radio")
        self.gridLayout_4.addWidget(self.provinces_radio, 0, 2, 1, 1)
        self.wards_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.wards_radio.setObjectName("wards_radio")
        self.gridLayout_4.addWidget(self.wards_radio, 1, 0, 1, 1)
        self.building_line_s_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.building_line_s_radio.setObjectName("building_line_s_radio")
        self.gridLayout_4.addWidget(self.building_line_s_radio, 1, 1, 1, 1)
        self.legal_s_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.legal_s_radio.setObjectName("legal_s_radio")
        self.gridLayout_4.addWidget(self.legal_s_radio, 1, 2, 1, 1)
        self.furniture_s_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.furniture_s_radio.setObjectName("furniture_s_radio")
        self.gridLayout_4.addWidget(self.furniture_s_radio, 1, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.field_container = QtWidgets.QGroupBox(parent=ProductSettings)
        self.field_container.setTitle("")
        self.field_container.setObjectName("field_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.field_container)
        self.horizontalLayout_2.setContentsMargins(8, 4, 8, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_en_container = QtWidgets.QWidget(parent=self.field_container)
        self.name_en_container.setStyleSheet("")
        self.name_en_container.setObjectName("name_en_container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.name_en_container)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_en_label = QtWidgets.QLabel(parent=self.name_en_container)
        self.name_en_label.setObjectName("name_en_label")
        self.verticalLayout_2.addWidget(self.name_en_label)
        self.name_en_input = QtWidgets.QLineEdit(parent=self.name_en_container)
        self.name_en_input.setObjectName("name_en_input")
        self.verticalLayout_2.addWidget(self.name_en_input)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.name_en_container)
        self.name_vi_container = QtWidgets.QWidget(parent=self.field_container)
        self.name_vi_container.setStyleSheet("")
        self.name_vi_container.setObjectName("name_vi_container")
        self.gridLayout = QtWidgets.QGridLayout(self.name_vi_container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_v_label = QtWidgets.QLabel(parent=self.name_vi_container)
        self.name_v_label.setObjectName("name_v_label")
        self.verticalLayout.addWidget(self.name_v_label)
        self.name_v_input = QtWidgets.QLineEdit(parent=self.name_vi_container)
        self.name_v_input.setObjectName("name_v_input")
        self.verticalLayout.addWidget(self.name_v_input)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.name_vi_container)
        self.value_container = QtWidgets.QWidget(parent=self.field_container)
        self.value_container.setStyleSheet("")
        self.value_container.setObjectName("value_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.value_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.value_label = QtWidgets.QLabel(parent=self.value_container)
        self.value_label.setObjectName("value_label")
        self.verticalLayout_3.addWidget(self.value_label)
        self.value_input = QtWidgets.QLineEdit(parent=self.value_container)
        self.value_input.setObjectName("value_input")
        self.verticalLayout_3.addWidget(self.value_input)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.value_container)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.field_container)
        self.tableView = QtWidgets.QTableView(parent=ProductSettings)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_4.addWidget(self.tableView)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ProductSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)

        self.retranslateUi(ProductSettings)
        self.buttonBox.accepted.connect(ProductSettings.accept) # type: ignore
        self.buttonBox.rejected.connect(ProductSettings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProductSettings)

    def retranslateUi(self, ProductSettings):
        _translate = QtCore.QCoreApplication.translate
        ProductSettings.setWindowTitle(_translate("ProductSettings", "Dialog"))
        self.categories_radio.setText(_translate("ProductSettings", "Categories"))
        self.districts_radio.setText(_translate("ProductSettings", "Districts"))
        self.options_radio.setText(_translate("ProductSettings", "Options"))
        self.provinces_radio.setText(_translate("ProductSettings", "Provinces"))
        self.wards_radio.setText(_translate("ProductSettings", "Wards"))
        self.building_line_s_radio.setText(_translate("ProductSettings", "Building line"))
        self.legal_s_radio.setText(_translate("ProductSettings", "Legal"))
        self.furniture_s_radio.setText(_translate("ProductSettings", "Funiture"))
        self.name_en_label.setText(_translate("ProductSettings", "name_en"))
        self.name_v_label.setText(_translate("ProductSettings", "name_vi"))
        self.value_label.setText(_translate("ProductSettings", "value"))
